# Writers for the site's static interface: site/_variables.yml and the
# site/generated/ tables. Every file is written atomically and carries a
# generated-file warning where the format permits. The Quarto site renders from
# these committed files alone; it never reads _targets/.

GENERATED_NOTE <- "Generated by the targets pipeline (_targets.R). Do not edit by hand."

write_lines_atomic <- function(lines, path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  tmp <- tempfile(tmpdir = dirname(path), fileext = ".tmp")
  con <- file(tmp, open = "wb")
  writeLines(enc2utf8(as.character(lines)), con, sep = "\n", useBytes = TRUE)
  close(con)
  if (!file.rename(tmp, path)) {
    unlink(tmp)
    stop("Could not write ", path, call. = FALSE)
  }
  path
}

fmt_num <- function(x, digits = 2) formatC(x, format = "f", digits = digits)
fmt_int <- function(x) formatC(x, format = "d", big.mark = ",")
fmt_ci <- function(est, lb, ub, digits = 2) paste0(fmt_num(est, digits), " [", fmt_num(lb, digits), ", ", fmt_num(ub, digits), "]")
fmt_p <- function(p) ifelse(p < 0.001, "< 0.001", fmt_num(p, 3))
# For prose: "p = 0.042" / "p < 0.001".
fmt_p_eq <- function(p) ifelse(p < 0.001, "< 0.001", paste("=", fmt_num(p, 3)))

md_escape <- function(x) gsub("|", "\\|", x, fixed = TRUE)

md_table <- function(df, align = NULL) {
  df[] <- lapply(df, function(col) md_escape(as.character(col)))
  align <- align %||% rep("l", ncol(df))
  rule <- vapply(align, function(a) switch(a, l = ":---", r = "---:", c = ":---:"), character(1))
  c(
    paste0("| ", paste(names(df), collapse = " | "), " |"),
    paste0("| ", paste(rule, collapse = " | "), " |"),
    apply(df, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |"))
  )
}

write_md <- function(lines, path) {
  write_lines_atomic(c(paste0("<!-- ", GENERATED_NOTE, " -->"), "", lines), path)
}

# ---- tables ----------------------------------------------------------------------

write_table_counts <- function(hub, schema, path) {
  df <- data.frame(
    Table = paste0("`", names(schema$tables), "`"),
    Rows = vapply(names(schema$tables), function(t) fmt_int(nrow(hub[[t]])), character(1)),
    Grain = vapply(schema$tables, function(t) t$grain, character(1)),
    Description = vapply(schema$tables, function(t) t$description, character(1)),
    check.names = FALSE
  )
  write_md(md_table(df, c("l", "r", "l", "l")), path)
}

write_study_characteristics <- function(hub, path) {
  pct <- function(x, level) {
    n <- sum(x == level, na.rm = TRUE)
    paste0(n, " (", round(100 * n / length(x)), "%)")
  }
  s <- hub$study
  a <- hub$arm
  training <- a[a$is_nontraining_control_group == "No", ]
  med_iqr <- function(x, digits = 1) {
    q <- stats::quantile(x, c(0.5, 0.25, 0.75), na.rm = TRUE)
    paste0(fmt_num(q[1], digits), " (", fmt_num(q[2], digits), "–", fmt_num(q[3], digits), ")")
  }
  df <- data.frame(
    Characteristic = c(
      "Studies", "Randomized", "Parallel-group design", "Within-participant design",
      "Includes a non-training control", "Arms (training / control)",
      "Participants per arm, median (IQR)", "Mean age of arm, median (IQR), years",
      "Arms with trained participants", "All-male arms", "All-female arms"
    ),
    Value = c(
      nrow(s), pct(s$randomized, "Yes"), pct(s$design, "Parallel Group"),
      paste0(sum(s$design != "Parallel Group"), " (", round(100 * mean(s$design != "Parallel Group")), "%)"),
      pct(s$control_condition, "Yes"),
      paste0(nrow(training), " / ", nrow(a) - nrow(training)),
      med_iqr(a$n, 0), med_iqr(a$age_m),
      paste0(sum(a$training_exp_m > 0, na.rm = TRUE), " of ", nrow(a)),
      paste0(sum(a$proportion_male == 1, na.rm = TRUE), " of ", nrow(a)),
      paste0(sum(a$proportion_male == 0, na.rm = TRUE), " of ", nrow(a))
    )
  )
  write_md(md_table(df, c("l", "r")), path)
}

write_pooled_table <- function(pooled, path) {
  df <- data.frame(
    Domain = pooled$domain,
    `Effect sizes` = pooled$k,
    Arms = pooled$n_arms,
    Studies = pooled$n_studies,
    `g [95% CI]` = fmt_ci(pooled$estimate, pooled$ci_lb, pooled$ci_ub),
    `95% prediction interval` = paste0("[", fmt_num(pooled$pi_lb), ", ", fmt_num(pooled$pi_ub), "]"),
    `τ² study / arm / effect` = paste(fmt_num(pooled$sigma2_study, 3), fmt_num(pooled$sigma2_arm, 3), fmt_num(pooled$sigma2_es, 3), sep = " / "),
    check.names = FALSE
  )
  write_md(md_table(df, c("l", "r", "r", "r", "r", "r", "r")), path)
}

write_moderator_table <- function(moderators, path) {
  df <- data.frame(
    Domain = moderators$domain,
    Term = moderators$term,
    `Estimate [95% CI]` = fmt_ci(moderators$estimate, moderators$ci_lb, moderators$ci_ub, 3),
    p = fmt_p(moderators$p_value),
    check.names = FALSE
  )
  write_md(md_table(df, c("l", "l", "r", "r")), path)
}

# ---- scalar variables ------------------------------------------------------------

write_site_variables <- function(hub, effect_sizes, pooled, moderators, project, path) {
  domain_results <- lapply(split(pooled, pooled$domain), function(p) {
    m <- moderators[moderators$domain == p$domain, ]
    load <- m[m$term == "Low vs. high load", ]
    sets <- m[m$term == "Per additional weekly set per exercise", ]
    list(
      k = p$k, arms = p$n_arms, studies = p$n_studies,
      g = fmt_num(p$estimate), g_ci = fmt_ci(p$estimate, p$ci_lb, p$ci_ub),
      pi = paste0("[", fmt_num(p$pi_lb), ", ", fmt_num(p$pi_ub), "]"),
      load_diff = fmt_ci(load$estimate, load$ci_lb, load$ci_ub),
      load_p = fmt_p_eq(load$p_value),
      sets_slope = fmt_ci(sets$estimate, sets$ci_lb, sets$ci_ub, 3),
      sets_p = fmt_p_eq(sets$p_value)
    )
  })
  names(domain_results) <- slugify(names(domain_results))
  vars <- list(
    hub = list(
      name = project$project$title,
      repo_url = project$project$repository,
      site_url = project$project$site_url
    ),
    counts = list(
      studies = nrow(hub$study),
      arms = nrow(hub$arm),
      participants = fmt_int(sum(hub$arm$n)),
      measures = nrow(hub$measure),
      outcome_rows = fmt_int(nrow(hub$outcome)),
      training_sets = fmt_int(nrow(hub$training_set)),
      effect_sizes = fmt_int(sum(!effect_sizes$is_control)),
      year_min = min(hub$study$year),
      year_max = max(hub$study$year)
    ),
    analysis = list(
      pre_post_r = project$analysis$pre_post_r,
      sets_centre = project$analysis$sets_centre,
      high_load_min_pct_1rm = project$analysis$high_load_min_pct_1rm,
      high_load_max_rm = project$analysis$high_load_max_rm
    ),
    results = domain_results
  )
  body <- yaml::as.yaml(vars)
  write_lines_atomic(c(paste0("# ", GENERATED_NOTE), body), path)
}

# ---- data dictionary -------------------------------------------------------------

# Markdown data dictionary rendered from config/schema.yml and the vocabulary
# file. Used for data/README.md and for the site's data page.
render_data_dictionary <- function(schema, vocabulary, heading_level = 2) {
  h <- function(level, text) paste(strrep("#", level), text)
  allowed <- function(spec) {
    v <- spec[["vocab"]] %||% spec[["vocab_list"]]
    if (is.null(v)) {
      bounds <- c(if (!is.null(spec$min)) paste("≥", spec$min), if (!is.null(spec$max)) paste("≤", spec$max))
      if (!is.null(spec$pattern)) bounds <- c(bounds, paste0("pattern `", spec$pattern, "`"))
      return(paste(bounds, collapse = ", "))
    }
    vals <- vocabulary$value[vocabulary$vocabulary == v]
    prefix <- if (!is.null(spec[["vocab_list"]])) "comma-separated list of " else ""
    if (length(vals) <= 6) paste0(prefix, paste0("`", vals, "`", collapse = ", ")) else paste0(prefix, "vocabulary `", v, "`")
  }
  out <- character()
  for (name in names(schema$tables)) {
    t <- schema$tables[[name]]
    fk <- vapply(t$foreign_keys, function(k) paste0("(", paste(k$columns, collapse = ", "), ") → `", k$references, "` (", paste(k$ref_columns, collapse = ", "), ")"), character(1))
    cols <- data.frame(
      Column = paste0("`", names(t$columns), "`"),
      Type = vapply(t$columns, function(c) c$type, character(1)),
      Required = vapply(t$columns, function(c) if (isTRUE(c$required)) "yes" else "", character(1)),
      Allowed = vapply(t$columns, allowed, character(1)),
      Description = vapply(t$columns, function(c) c$description %||% "", character(1)),
      check.names = FALSE
    )
    out <- c(
      out,
      h(heading_level, paste0("`", name, "`")), "",
      t$description, "",
      paste0("- **File:** `", t$file, "`"),
      paste0("- **One row per:** ", t$grain),
      paste0("- **Primary key:** (", paste(t$primary_key, collapse = ", "), ")"),
      if (length(fk)) paste0("- **Foreign keys:** ", paste(fk, collapse = "; ")),
      "", md_table(cols), ""
    )
  }
  vocab_names <- unique(vocabulary$vocabulary)
  out <- c(out, h(heading_level, "Controlled vocabularies"), "",
    paste0("Defined in `", schema$vocabulary_file, "`. Values are case-sensitive."), "")
  for (v in vocab_names) {
    rows <- vocabulary[vocabulary$vocabulary == v, ]
    desc <- ifelse(is.na(rows$description), "", rows$description)
    out <- c(out, h(heading_level + 1, paste0("`", v, "`")), "",
      md_table(data.frame(Value = paste0("`", rows$value, "`"), Description = desc)), "")
  }
  out
}

# Full text of data/README.md (regenerate with scripts/build_data_dictionary.R).
build_data_readme <- function(schema, vocabulary) {
  unname(c(
    "<!-- Generated from config/schema.yml by scripts/build_data_dictionary.R. Do not edit by hand. -->",
    "",
    "# Data dictionary",
    "",
    "> **These tables contain synthetic toy data.** They reproduce the structure of a real",
    "> resistance-training extraction corpus, but every study, author, DOI and value is invented",
    "> (see `data-raw/generate_toy_data.R`). Do not use them for inference.",
    "",
    "One CSV per normalized entity, joined by stable identifiers that are assigned once and never",
    "reused or renumbered. Files are UTF-8, comma-separated, LF line endings, with an empty field",
    "meaning *missing* (the literal text `NA` is a value, and will fail vocabulary checks).",
    "",
    "Every rule below is enforced by `R/validate.R` on each pull request",
    "(`.github/workflows/validate-data.yml`). To add or change a column, edit",
    "`config/schema.yml`, regenerate this file, and update the affected CSVs in the same pull request.",
    "",
    "## How the tables relate",
    "",
    "- `study` has many `arm`s and many `measure`s.",
    "- `arm` has many `arm_week`s (its timeline); each `arm_week` has many `training_set`s.",
    "- `outcome` and `contrast` rows each reference an arm-week *and* a measure, which must belong",
    "  to the same study.",
    "- `reliability` rows reference a `measure`.",
    "",
    render_data_dictionary(schema, vocabulary, heading_level = 2)
  ))
}

write_data_dictionary <- function(schema, vocabulary, path) {
  write_md(render_data_dictionary(schema, vocabulary, heading_level = 2), path)
}
